### ISSUE TITLE
V6 component overhaul.

### ISSUE THREAD

**Issue by JSideris** [JSideris/DOThtml#157]
This task could be broken down further. These are misc thoughts on component usage that could be improved prior to the v6 launch.

- [x] Remove non-component bindings #155 
- [ ] Event emitter pattern #146 
- [x] Better encapsulation for components #168
- [x] Component vdoms should be more abstract rather than rendered elements. #158
- [ ] Find a way to resolve the annoying binding problem. Right now, we need to instantiate components and assign them to a variable to bind them. There should be a more convenient way to do this (inline).
- [x] Find a way to attach events and attributes to components inline #177
- [x] Get rid of abstract component #153 
- [ ] Remove css parameter from style builder #145 
- [x] ~~There should be an easy way for a binding in a component to be synced with a child component.~~ We seem to have gotten this for free with reactives.

**Comment by JSideris** [comment]
I have implemented the event emitter pattern (via the  method) and robust prop validation with custom validators and default value factories.
